"""add parent accounts

Revision ID: 80dc1c5f6a75
Revises: 29164cf24041
Create Date: 2026-09-22 23:00:38.599141

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80dc1c5f6a75'
down_revision: str | Sequence[str] | None = '29164cf24041'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('child', sa.Column('parent_id', sa.Integer(), nullable=True))
    # named explicitly — autogenerate leaves this unnamed by default, which
    # lets Postgres pick a name and leaves downgrade() unable to target it
    op.create_foreign_key('fk_child_parent_id', 'child', 'parent', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_child_parent_id', 'child', type_='foreignkey')
    op.drop_column('child', 'parent_id')
    op.drop_table('parent')
    # ### end Alembic commands ###
