"""add problem fields to attempt

Revision ID: bd82286e7c1c
Revises: 961c6ea01866
Create Date: 2026-09-22 20:44:22.967456

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd82286e7c1c'
down_revision: str | Sequence[str] | None = '961c6ea01866'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('operand_a', sa.Integer(), nullable=False))
    op.add_column('attempt', sa.Column('operand_b', sa.Integer(), nullable=False))
    op.add_column('attempt', sa.Column('submitted_answer', sa.Integer(), nullable=True))
    op.add_column('attempt', sa.Column('answered_at', sa.DateTime(), nullable=True))
    op.alter_column('attempt', 'correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempt', 'correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('attempt', 'answered_at')
    op.drop_column('attempt', 'submitted_answer')
    op.drop_column('attempt', 'operand_b')
    op.drop_column('attempt', 'operand_a')
    # ### end Alembic commands ###
